version: '3.4'

services:
  web:
    # image: stoyan02/employee-system
    build: ./employee_management_sys
    command: gunicorn employee_management_sys.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./employee_management_sys/static:/tmp/employee_management_sys/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./employee_management_sys/employee_management_sys/.env
    depends_on:
      - postgres
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: employee_system
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./employee_management_sys/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web