# Generated by Django 4.1.1 on 2022-12-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['name']},
        ),
    ]
