# Generated by Django 4.1.3 on 2022-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_table'),
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cells',
            name='employee',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
