# Generated by Django 4.1.3 on 2022-11-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_cells_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cells',
            name='employee',
        ),
    ]
