# Generated by Django 4.1.3 on 2022-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_remove_cells_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='cell_name',
            field=models.CharField(max_length=25),
        ),
    ]
