# Generated by Django 4.1.3 on 2022-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_alter_cells_cell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='cell_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
