# Generated by Django 4.1.3 on 2022-11-12 20:58

import django.core.validators
from django.db import migrations, models
import employee_management_sys.base.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[employee_management_sys.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=40, validators=[employee_management_sys.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)])),
                ('cell', models.CharField(blank=True, default='Not Assigned', max_length=10)),
                ('emp_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
