# Generated by Django 4.1.3 on 2022-11-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='cells_Cells',
        ),
    ]
