# Generated by Django 4.1.3 on 2022-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='cell',
            field=models.CharField(blank=True, choices=[('C01', 'C01'), ('C02', 'C02'), ('C03', 'C03'), ('C04', 'C04'), ('C05', 'C05'), ('Not Assigned', 'Not Assigned')], default='Not Assigned', max_length=50),
        ),
    ]
