# Generated by Django 4.1.3 on 2022-11-12 22:14

import django.core.validators
from django.db import migrations, models
import employee_management_sys.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_cell_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=7, unique=True, verbose_name='Employee Id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=40, validators=[employee_management_sys.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, validators=[employee_management_sys.base.validators.validate_only_letters, django.core.validators.MinLengthValidator(2)], verbose_name='Last Name'),
        ),
    ]
