# Generated by Django 4.1.3 on 2022-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_remove_cells_employee'),
        ('employees', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cell',
        ),
        migrations.AddField(
            model_name='employee',
            name='cell',
            field=models.ManyToManyField(to='cells.cells'),
        ),
    ]
