# Generated by Django 4.1.3 on 2022-12-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_cell_employee_cell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
    ]
