# Generated by Django 4.1.3 on 2022-11-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employeetocells'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeToCells',
        ),
    ]
