# Generated by Django 4.1.3 on 2022-12-05 19:21

import django.core.validators
from django.db import migrations, models
import employee_management_sys.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_employeemanager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanager',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeemanager',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), employee_management_sys.base.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='employeemanager',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), employee_management_sys.base.validators.validate_only_letters]),
        ),
    ]
