version: '3.4'

services:
  web:
    build: ./employee_management_sys
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./employee_management_sys/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./employee_management_sys/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB: employee_management
      PGDATA: /var/lib/employee_management/data/pgdata
    volumes:
      - ./employee_management/:/var/lib/employee_management/data