# Generated by Django 4.1.3 on 2022-12-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0005_alter_cells_cell_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(max_length=255)),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cells.cells')),
            ],
        ),
    ]
