# Generated by Django 4.1.3 on 2022-12-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['name']},
        ),
    ]
